import 'animate.css';
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Theme from "@/components/Theme";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wesley Fernandes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // biome-ignore lint/a11y/useValidLang: <explanation>
    <html lang="pt-br">
      <body className={inter.className}>
        <Theme>
          <Layout>{children}</Layout>
        </Theme>
      </body>
    </html>
  );
}
